[tool.poetry]
name = "repl_python3_my"
version = "0.1.0"
description = ""
authors = ["soobinkim-kor <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
np = "^1.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
